<a href="https://colab.research.google.com/github/kompallyGyaneshwar215/DS-Lab/blob/main/Lab_8__1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Week 8: Implement & Analyze linear algebra and matrix decomposition methods for computational applications.

In [ ]:
import numpy as np
def lu_decomposition(A):
    n = len(A)
    # Initialize L and U matrices
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    for i in range(n):
        for k in range(i, n):
            sum_upper = 0
            for j in range(i):
                sum_upper += L[i][j] * U[j][k]
            U[i][k] = A[i][k] - sum_upper
        L[i][i] = 1  # Diagonal as 1
        for k in range(i + 1, n):
            sum_lower = 0
            for j in range(i):
                sum_lower += L[k][j] * U[j][i]
            L[k][i] = (A[k][i] - sum_lower) / U[i][i]
    return L, U
def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)
    for i in range(n):
        sum_value = 0
        for j in range(i):
            sum_value += L[i][j] * y[j]
        y[i] = b[i] - sum_value
    return y
def backward_substitution(U, y):
    n = len(U)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        sum_value = 0
        for j in range(i + 1, n):
            sum_value += U[i][j] * x[j]
        x[i] = (y[i] - sum_value) / U[i][i]
    return x
A = np.array([
    [2, -1, -2],
    [-4, 6, 3],
    [-4, -2, 8]
], dtype=float)
b = np.array([-2, 9, -5], dtype=float)
L, U = lu_decomposition(A)
y = forward_substitution(L, b)
x = backward_substitution(U, y)
print("Matrix A:")
print(A)
print("\nLower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)
print("\nIntermediate Solution y:")
print(y)
print("\nFinal Solution x:")
print(x)



Matrix A:
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]

Lower Triangular Matrix L:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]

Upper Triangular Matrix U:
[[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]]

Intermediate Solution y:
[-2.  5. -4.]

Final Solution x:
[-1.875       0.91666667 -1.33333333]


8.2.  QR Decomposition

In [ ]:
import numpy as np
def qr_decomposition(A):
    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    return Q, R
def solve_qr(Q, R, b):
    y = np.dot(Q.T, b)
    n = R.shape[0]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        sum_value = 0
        for j in range(i + 1, n):
            sum_value += R[i, j] * x[j]

        x[i] = (y[i] - sum_value) / R[i, i]
    return x
# Input Matrix A
A = np.array([
    [1, 1, 0],
    [1, 0, 1],
    [0, 1, 1]
], dtype=float)
b = np.array([4, 5, 6], dtype=float)
Q, R = qr_decomposition(A)
x = solve_qr(Q, R, b)
print("Matrix A:")
print(A)
print("\nOrthogonal Matrix Q:")
print(Q)
print("\nUpper Triangular Matrix R:")
print(R)
print("\nSolution Vector x:")
print(x)



Matrix A:
[[1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]]

Orthogonal Matrix Q:
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]

Upper Triangular Matrix R:
[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]

Solution Vector x:
[1.5 2.5 3.5]
